spring.application.name=college_schedule
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=control_asistance
spring.datasource.password=12345678
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
server.port=8081